### ISSUE TITLE
Can't update to 3.3.0

### ISSUE THREAD

**Issue by chocolata** [OFFLINE-GmbH/oc-mall-plugin#1143]
Hi, just wanted to update to the most recent version to make use of all the bugfixes of the Mall plugin, but I'm getting the following error:

```
Problem 1
    - Root composer.json requires offline/oc-mall-plugin ^3.3, it is satisfiable by offline/oc-mall-plugin[v3.3.0] from composer repo (https://repo.packagist.org) but offline/oc-mall-plugin[dev-mjauvin-winter-compat, dev-master, dev-mollie, dev-next, dev-develop, dev-pick_up_at_store, v1.0.4, ..., v1.x-dev, v2.0.0, ..., v2.x-dev, v3.0.0, ..., v3.2.1] from composer repo (https://gateway.octobercms.com) has higher repository priority. The packages from the higher priority repository do not match your constraint and are therefore not installable. That repository is canonical so the lower priority repo's packages are not installable. See https://getcomposer.org/repoprio for details and assistance.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
```

If I keep my composer.json file like below, the update is ignored:

```
    "require": {
        "php": "^8.0.2",
        "october/rain": "^3.2",
        "laravel/framework": "^9.0",
        "october/all": "^3.1",
        "offline/oc-mall-plugin": "^3.0",
        "blakejones/themelink-plugin": "^1.1",
        "vojtasvoboda/twigextensions-plugin": "^2.0",
        "romanov/clearcachewidget-plugin": "^1.3",
        "vdlp/oc-redirect-plugin": "^3.1",
        "rainlab/pages-plugin": "^2.0",
        "rainlab/builder-plugin": "^2.0",
        "rainlab/location-plugin": "^1.0",
        "rainlab/translate-plugin": "^2.2",
        "ginopane/awesomeiconslist-plugin": "^1.3",
        "offline/oc-site-search-plugin": "^1.7",
        "simplesoftwareio/simple-qrcode": "^4.2",
        "rainlab/googleanalytics-plugin": "^2.0",
        "responsiv/campaign-plugin": "^3.0",
        "renatio/maillog-plugin": "^1.0"
    },
```

If I change the line ` "offline/oc-mall-plugin": "^3.0",` to  `"offline/oc-mall-plugin": "^3.3",` I get the above error. I might be overlooking something stupid, but could you kindly help me figure out why I cannot upgrade to the most recent version.

Thanks.

**Comment by SamBrishes** [comment]
Hello,

thanks for reporting this issue.

Seems like @tobias-kuendig's quotes used in ['v3.3.0' changelog entry](https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/16748563ddb050e67f9afe6d577e3871bd6cdc88/updates/version.yaml#L574) caused an error in the version comparison / handling within October's repository. That's Intresting. However, I fixed the `version.yaml` file, you should now be able to update the package accordingly. I recommend using 

```sh
composer update "offline/oc-mall-plugin:^3.3"
```

instead of updating the `composer.json` file manually.

Sincerely,\
Sam.

**Comment by tobias-kuendig** [comment]
@chocolata is the error still happening? The entry in the `versions.yaml` has no effect on composer. The problem from your error message is that you want oc-mall-plugin ^3.3, which is available on packagist but not on October's repo.

I just double checked and the 3.3.0 release is on October's repo just fine, so it would be interessting to know if the problem is still around or if you just happened to update before the release was published.

**Comment by SamBrishes** [comment]
That's strange. I had the same error as @chocolata, but after I changed the `versions.yaml` file it worked again.  

According to the error message and the troubleshooting (via the file), it seemed that the OC repository could not recognise (or register) the v3.3.0 tag due to the single quotes.

**Comment by tobias-kuendig** [comment]
The version seems to be detected just fine:

![grafik](https://github.com/OFFLINE-GmbH/oc-mall-plugin/assets/8600029/fd24b990-bbde-4733-a7b7-d55864b46001)

**Comment by chocolata** [comment]
Thanks @tobias-kuendig I can just add it explicitly in my composer file, right? Because it wasn't present there out of the box.
