### ISSUE TITLE
Single Article Filter options do not update themselves

### ISSUE THREAD

**Issue by amdad** [OFFLINE-GmbH/oc-mall-plugin#62]
When you update Variant/s Properties data, frontend Filters reflects that right away. Show up new filter options or remove ones. Works perfectly.
But when you change Single Article Properties.. nothing visible change on Filters part.
I checked on both local and server. The same issue.

Related to issue #59, since it fixed visibility of Single Articles on product list, but still not yet Filter options.

**Comment by tobias-kuendig** [comment]
Thanks for pointing this out. It should be fixed in 0f07832.

Can you try again?

**Comment by amdad** [comment]
Sorry, didn't see notice about reply.  Tested, but not works yet. I refreshed dem data to be sure.  
Best to test it out on clean DB with just single article to see there is no data in filters panel after create/update.

**Comment by amdad** [comment]
Good news is after optimize the code in https://github.com/OFFLINE-GmbH/oc-mall-plugin/commit/0f07832f88316e64c0c2526bceaa9887693542f5, Variants index updates still works. But Single Articles still not, so problem must be somewhere else.

**Comment by tobias-kuendig** [comment]
Can you confirm this has been fixed in af1a3784b6f70a218a953dad7fd656380aee6770?

**Comment by amdad** [comment]
I tried to with latest commit https://github.com/OFFLINE-GmbH/oc-mall-plugin/commit/79cc810ae70741c5c75139a314683542fecddf23. Everything works then but page load time around get even up to 18 seconds. 
With commit you point out https://github.com/OFFLINE-GmbH/oc-mall-plugin/commit/af1a3784b6f70a218a953dad7fd656380aee6770 it didn't work.
Error on

>CartSession.php line 20

So commits somewhere in the middle should be working. 

Any idea why latest version https://github.com/OFFLINE-GmbH/oc-mall-plugin/commit/79cc810ae70741c5c75139a314683542fecddf23 slow down so much? You test some new things?  CLI commands looks cool now.

**Comment by amdad** [comment]
YEAH, seems working now. There was some problems on my DB side at first,  Will test it further for a while and close the issue in result. Thanks a lot!
